# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-11 10:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_owner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_image',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='business',
            name='shops',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='business_owner.Shop'),
        ),
    ]
