# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-11 10:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_owner', '0004_auto_20180911_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='shops',
        ),
        migrations.AddField(
            model_name='business',
            name='shops',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='business_owner.Shop'),
        ),
        migrations.RemoveField(
            model_name='shop',
            name='chairs',
        ),
        migrations.AddField(
            model_name='shop',
            name='chairs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='business_owner.Chair'),
        ),
    ]
