# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-10 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='chairs',
            field=models.IntegerField(default=1),
        ),
    ]
