# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-10 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_shop_chairs'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='allows_bookings',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shop',
            name='allows_walk_in',
            field=models.BooleanField(default=False),
        ),
    ]
