# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-10 12:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20180910_1216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='allows_walk_in',
            new_name='allows_walk_ins',
        ),
    ]
