# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-10 12:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20180910_1217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='allows_bookings',
            new_name='bookings',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='allows_walk_ins',
            new_name='walk_ins',
        ),
    ]
