# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-10 12:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20180910_1218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='syle',
            new_name='style',
        ),
    ]
