# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-10 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20180910_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chair',
            name='duration_weeks',
            field=models.IntegerField(default=1),
        ),
    ]
