# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-10 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20180910_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='chair',
            name='for_shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Shop'),
        ),
    ]
