# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-10 18:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_chair_for_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chair',
            name='for_shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Shop'),
        ),
    ]
