# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-10 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20180910_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chair',
            name='for_shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Shop'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='chairs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.Chair'),
        ),
    ]
