# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-10 18:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_chair_for_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chair',
            name='for_shop',
        ),
    ]
