# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-11 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='chairs',
        ),
        migrations.AddField(
            model_name='shop',
            name='chairs',
            field=models.ManyToManyField(blank=True, to='business.Chair'),
        ),
    ]
