# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-11 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_auto_20180911_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='chairs',
        ),
        migrations.AddField(
            model_name='shop',
            name='chairs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.Chair'),
        ),
    ]
