# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-11 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_auto_20180911_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='chair',
            name='r_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.Shop'),
        ),
    ]
