# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-13 12:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_auto_20180913_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_time', models.TimeField(default=datetime.datetime(2018, 9, 13, 9, 0))),
                ('closing_time', models.TimeField(default=datetime.datetime(2018, 9, 13, 17, 30))),
            ],
        ),
        migrations.AddField(
            model_name='shop',
            name='week_day_trading_hours',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='normal_trading_hours', to='business.TradingHours'),
        ),
        migrations.AddField(
            model_name='shop',
            name='weekend_trading_hours',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekend_trading_hours', to='business.TradingHours'),
        ),
    ]
