# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-17 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_business_shops'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
