# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-18 09:58
from __future__ import unicode_literals

import address.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_auto_20180918_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='address',
            field=address.models.AddressField(null=True, on_delete=django.db.models.deletion.CASCADE, to='address.Address'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2018, 9, 25, 9, 58, 5, 265357), null=True),
        ),
    ]
