# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-11 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_auto_20180911_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chair',
            old_name='r_id',
            new_name='p_id',
        ),
        migrations.AddField(
            model_name='shop',
            name='p_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business.Business'),
        ),
    ]
