# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-13 12:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_tradinghours_shop_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='weekend_trading_hours',
        ),
        migrations.AlterField(
            model_name='shop',
            name='week_day_trading_hours',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.TradingHours'),
        ),
    ]
