# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-17 11:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_auto_20180917_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chair',
            name='shop_id',
        ),
    ]
