# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-11 16:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_auto_20180911_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chair',
            name='p_id',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='p_id',
        ),
    ]
