# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-13 12:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_auto_20180913_1228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='week_day_trading_hours',
            new_name='trading_hours',
        ),
        migrations.RemoveField(
            model_name='chair',
            name='shop_id',
        ),
    ]
