# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-11 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_auto_20180911_1807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='business_id',
            new_name='p_id',
        ),
        migrations.RemoveField(
            model_name='chair',
            name='shop_id',
        ),
        migrations.AddField(
            model_name='chair',
            name='p_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business.Shop'),
        ),
    ]
