# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-18 10:25
from __future__ import unicode_literals

import address.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_auto_20180918_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='address',
            field=address.models.AddressField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_id', to='address.Address'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2018, 9, 25, 10, 25, 17, 215726), null=True),
        ),
    ]
