# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-13 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_remove_chair_time_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='chair',
            name='time_slots',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business.TimeSlot'),
        ),
    ]
