# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-12 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0012_auto_20180912_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='chairs',
        ),
        migrations.AddField(
            model_name='shop',
            name='chairs',
            field=models.ManyToManyField(to='business.Chair'),
        ),
    ]
