# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-17 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_auto_20180917_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chair',
            name='shop_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='business.Shop'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='chairs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.Chair', to_field='shop_id'),
        ),
    ]
