# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-12 17:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0014_chair_shop_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='chairs',
        ),
        migrations.AddField(
            model_name='shop',
            name='chairs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business.Chair'),
        ),
    ]
