# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-13 20:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0016_remove_chair_time_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='chairs',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='business.Chair'),
        ),
    ]
