# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-18 11:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0017_auto_20180918_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenCloseTimes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_time', models.TimeField(default=datetime.datetime(2018, 9, 18, 9, 0))),
                ('closing_time', models.TimeField(default=datetime.datetime(2018, 9, 18, 17, 30))),
                ('closed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TradingTimes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='shop',
            name='closing_time',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='opening_time',
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2018, 9, 25, 11, 11, 58, 697635), null=True),
        ),
        migrations.AddField(
            model_name='tradingtimes',
            name='shop_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='business.Shop'),
        ),
        migrations.AddField(
            model_name='shop',
            name='trading_times',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business.TradingTimes'),
        ),
    ]
