# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-17 12:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0022_auto_20180917_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chair',
            name='shop_id',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='business.Shop'),
        ),
    ]
