# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-17 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0024_auto_20180917_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chair',
            name='shop_id',
        ),
        migrations.AddField(
            model_name='chair',
            name='parent_shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business.Shop'),
        ),
    ]
