# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-17 13:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0025_auto_20180917_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chair',
            name='parent_shop',
        ),
        migrations.AddField(
            model_name='chair',
            name='shop_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='business.Shop'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='chairs',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.Chair'),
        ),
    ]
