# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-13 20:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0026_auto_20180913_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='trading_hours',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.TradingHours'),
        ),
    ]
