# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-17 13:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0026_auto_20180917_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='shops',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.Shop'),
        ),
    ]
