# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-13 21:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0029_auto_20180913_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='chairs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business.Chair'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='trading_hours',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.TradingHours'),
        ),
    ]
