# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-17 14:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0031_chair_time_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='end',
        ),
    ]
