# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-17 14:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0032_remove_timeslot_end'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeslot',
            old_name='start',
            new_name='start_date',
        ),
    ]
