# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-17 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0033_auto_20180917_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
