# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-17 14:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0035_auto_20180917_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2018, 9, 24, 14, 33, 31, 938617), null=True),
        ),
    ]
