# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-13 21:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0035_auto_20180913_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradinghours',
            name='shop_id',
        ),
    ]
