# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-13 21:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0036_remove_tradinghours_shop_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='chairs',
        ),
    ]
