# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-17 14:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0036_auto_20180917_1433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chair',
            old_name='time_slot',
            new_name='time_slots',
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2018, 9, 24, 14, 39, 57, 169878), null=True),
        ),
    ]
