# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-18 11:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0037_auto_20180918_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='trading_times',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.TradingTimes'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2018, 9, 25, 11, 50, 27, 934978), null=True),
        ),
        migrations.AlterField(
            model_name='tradingtimes',
            name='monday',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='M', to='business.OpenCloseTimes'),
        ),
    ]
