# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-13 21:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0037_remove_shop_chairs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='chair_id',
        ),
    ]
