# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-17 15:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0037_auto_20180917_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chair',
            name='time_slots',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.TimeSlot'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2018, 9, 24, 15, 5, 27, 927765), null=True),
        ),
    ]
