# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-13 21:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0038_remove_timeslot_chair_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='trading_hours',
        ),
        migrations.AddField(
            model_name='shop',
            name='closing_time',
            field=models.TimeField(default=datetime.datetime(2018, 9, 13, 17, 30)),
        ),
        migrations.AddField(
            model_name='shop',
            name='opening_time',
            field=models.TimeField(default=datetime.datetime(2018, 9, 13, 9, 0)),
        ),
        migrations.DeleteModel(
            name='TradingHours',
        ),
    ]
