# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-17 15:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0038_auto_20180917_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2018, 9, 24, 15, 8, 11, 678971), null=True),
        ),
    ]
