# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-13 22:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0039_auto_20180913_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chair',
            name='time_slots',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='chair_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business.Chair'),
        ),
    ]
