# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-18 12:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0044_auto_20180918_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2018, 9, 25, 12, 2, 8, 402005), null=True),
        ),
        migrations.AlterField(
            model_name='tradingtimes',
            name='shop_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='business.Shop'),
        ),
    ]
