# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-18 12:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0045_auto_20180918_1202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='trading_times',
            new_name='trading_time',
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2018, 9, 25, 12, 4, 25, 859007), null=True),
        ),
    ]
