# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-18 12:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0046_auto_20180918_1204'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TradingTimes',
            new_name='TradingTime',
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2018, 9, 25, 12, 6, 11, 494495), null=True),
        ),
    ]
