# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-18 12:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0058_auto_20180918_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openclosetimes',
            name='trading_time_id',
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2018, 9, 25, 12, 30, 5, 11186), null=True),
        ),
    ]
