# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-18 12:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0059_auto_20180918_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradingtime',
            name='friday',
        ),
        migrations.RemoveField(
            model_name='tradingtime',
            name='monday',
        ),
        migrations.RemoveField(
            model_name='tradingtime',
            name='saturday',
        ),
        migrations.RemoveField(
            model_name='tradingtime',
            name='sunday',
        ),
        migrations.RemoveField(
            model_name='tradingtime',
            name='thursday',
        ),
        migrations.RemoveField(
            model_name='tradingtime',
            name='tuesday',
        ),
        migrations.RemoveField(
            model_name='tradingtime',
            name='wednesday',
        ),
        migrations.AddField(
            model_name='tradingtime',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tradingtime',
            name='closing_time',
            field=models.TimeField(default=datetime.datetime(2018, 9, 18, 17, 30)),
        ),
        migrations.AddField(
            model_name='tradingtime',
            name='opening_time',
            field=models.TimeField(default=datetime.datetime(2018, 9, 18, 9, 0)),
        ),
        migrations.AlterField(
            model_name='shop',
            name='trading_time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business.TradingTime'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2018, 9, 25, 12, 34, 57, 180995), null=True),
        ),
        migrations.AlterField(
            model_name='tradingtime',
            name='shop_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='business.Shop'),
        ),
    ]
