# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-18 12:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0064_auto_20180918_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeTimes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.TimeField(default=datetime.datetime(2018, 9, 18, 9, 0))),
            ],
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2018, 9, 25, 12, 53, 4, 824849), null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='hours',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business.TradeTimes'),
        ),
    ]
