# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-18 13:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0073_auto_20180918_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradetime',
            name='friday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friday', to='business.DayTradeTime'),
        ),
        migrations.AddField(
            model_name='tradetime',
            name='saturday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saturday', to='business.DayTradeTime'),
        ),
        migrations.AddField(
            model_name='tradetime',
            name='sunday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sunday', to='business.DayTradeTime'),
        ),
        migrations.AddField(
            model_name='tradetime',
            name='thursday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thursday', to='business.DayTradeTime'),
        ),
        migrations.AddField(
            model_name='tradetime',
            name='wednesday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wednesday', to='business.DayTradeTime'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2018, 9, 25, 13, 9, 18, 85041), null=True),
        ),
    ]
