# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-19 08:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0090_auto_20180918_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayOfWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business.Shop')),
            ],
        ),
        migrations.AlterField(
            model_name='daytradetime',
            name='closes_at',
            field=models.TimeField(default=datetime.datetime(2018, 9, 19, 17, 30)),
        ),
        migrations.AlterField(
            model_name='daytradetime',
            name='opens_at',
            field=models.TimeField(default=datetime.datetime(2018, 9, 19, 9, 0)),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2018, 9, 26, 8, 48, 1, 462225), null=True),
        ),
    ]
