# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-19 09:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0091_auto_20180919_0848'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayTradeDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('opens_at', models.TimeField(default=datetime.datetime(2018, 9, 19, 9, 0))),
                ('closes_at', models.TimeField(default=datetime.datetime(2018, 9, 19, 17, 30))),
                ('closed', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='dayofweek',
            name='shop_id',
        ),
        migrations.RemoveField(
            model_name='daytradetime',
            name='shop_id',
        ),
        migrations.RemoveField(
            model_name='tradetime',
            name='friday',
        ),
        migrations.RemoveField(
            model_name='tradetime',
            name='monday',
        ),
        migrations.RemoveField(
            model_name='tradetime',
            name='saturday',
        ),
        migrations.RemoveField(
            model_name='tradetime',
            name='shop_id',
        ),
        migrations.RemoveField(
            model_name='tradetime',
            name='sunday',
        ),
        migrations.RemoveField(
            model_name='tradetime',
            name='thursday',
        ),
        migrations.RemoveField(
            model_name='tradetime',
            name='tuesday',
        ),
        migrations.RemoveField(
            model_name='tradetime',
            name='wednesday',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='hours',
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2018, 9, 26, 9, 3, 53, 55538), null=True),
        ),
        migrations.DeleteModel(
            name='DayOfWeek',
        ),
        migrations.DeleteModel(
            name='DayTradeTime',
        ),
        migrations.DeleteModel(
            name='TradeTime',
        ),
        migrations.AddField(
            model_name='daytradedetail',
            name='shop_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business.Shop'),
        ),
    ]
