# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-19 09:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0094_auto_20180919_0907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daytradedetail',
            old_name='closes_at',
            new_name='closes',
        ),
        migrations.RenameField(
            model_name='daytradedetail',
            old_name='opens_at',
            new_name='opens',
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2018, 9, 26, 9, 9, 26, 390885), null=True),
        ),
    ]
