# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-19 10:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0104_auto_20180919_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='closed_on_public_holidays',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2018, 9, 26, 10, 25, 5, 154436), null=True),
        ),
    ]
