# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-19 10:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0105_auto_20180919_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopdaytrade',
            name='day',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2018, 9, 26, 10, 29, 21, 519248), null=True),
        ),
    ]
