# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-19 10:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0108_auto_20180919_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2018, 9, 26, 10, 42, 57, 497414), null=True),
        ),
    ]
