# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-19 12:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0117_auto_20180919_1113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopdaytrade',
            old_name='days',
            new_name='day',
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2018, 9, 26, 12, 58, 16, 239627), null=True),
        ),
    ]
